### PR TITLE
Add translations and new UI to info pages

### PR DESCRIPTION
**Pull request by sgomez**
New UI based in [tailwindcss](https://tailwindcss.com/). Assets will be compiled and added to the repository, but until the PR was marked as a draft, node will be required to see the changes:

```
yarn install
yarn dev
```
List of templates to be updated:

- [x] Info
- [x] About
- [x] Support
- [x] Privacy

### CODE REVIEW

**Comment by sgomez** [comment]
@surfnet-niels, in 8c617cf the current templates are updated to use the same translations. This PR uses [feature flags](https://trunkbaseddevelopment.com/feature-flags/) to enable the new UI, so I'd like to propose to rename this PR to 'Add translations and new UI to info pages'. 

That means that it could be merged to master branch. In edu.nl the feature will be disabled (by default). With feature flags it could be easy to share new features between @mrvanes and me, and only enable in production when there are done.

The opposite is to create branches from other branches and synchronizing changes between them that requires a lot of merges or rebases.

**Comment by thijskh** [comment]
The code changes look ok, but I will have to test it out a bit in practice to get more feeling for it.

**Comment by thijskh** [comment]
Technically it works.

What is the motivation to remove the big centered login button and hide it a bit away on the top-left?

On mobile the login button is even hidden away in a menu.

The main informational texts are now not readable above the fold.

I think I'm missing a bit where this design comes from and what the stories behind it are, I think. What motivates these ui changes and what are the ideas behind the design?

**Comment by sgomez** [comment]
> What is the motivation to remove the big centered login button and hide it a bit away on the top-right?

Usability. It is the usual place to put login buttons and menu options in desktops layouts. We need to create a menu to select language, admin options, and future use like profile removal).

> On mobile the login button is even hidden away in a menu.

That is because the login button is pretty big and I couldn't put in the topbar menu in mobile layouts. We can left the button in the hero section in both cases or only in mobiles.

> The main informational texts are now not readable above the fold.

I can do the hero section smallest in mobile layout. Anyway, the information text won't be always fully readable, depends of the language and the mobile resolution.

> I think I'm missing a bit where this design comes from and what the stories behind it are. What motivates these ui changes and what are the ideas behind the design?

I did a mockup a long time ago but now I realized that probably you dind't see it. I started that because no one discussed the changes.  Sorry about that.

The motivations are:

- Create a better responsive design, removing tables with flex grids.
- We need to add the language button in top menu. Usually an user will require to change the language before to do login. 
- Another usability issue is to have icons as action links. Menus options and actions links should be labels or labels plus icons. I'd like to change all with button that requires more space. An icon can be ambiguous and forces the user to go to the icon and wait for the popover (and this in mobiles are not possible).
- Like we will have an API, could be smart to create a react application instead to have a server side rendered application. Less server load and the user can feel that the application runs fast. 
- Tailwindcss is a lightweight css framework, that supports dark mode. Very close to have a pure css design. And AFAIK Tailwind works better than bootstrap with React styled components.

Another behaviors I'd like to change:

-  When the user is logged and he goes to the main page, he can see the login button again. This commits detects when the user is logged in homepage and redirect him automatically to the index manage page. So, main page is only visible if you are not logged. (this is in commit 415a1fa in this PR, so if you don't like I can revert it) 
- Some admin controllers uses regular user controllers and return the flow to them. For example, to delete a link as admin, you use Manager Delete controller. This will send the admin to the user link lists instead left him in the admin link list page. 
- We have this use case in the incubator with institutional portals: `An institution could have regular users, community managers (CM) and administrators. A regular user only can create random shorts url, a CM can create custom shorts urls but cannot admin the application, admins can do anything.` So it could be better than in the manage index page, the form adds the custom short url input only if you are a CM or an admin. The admin controllers and pages will disappears in favor of easyadmin, only available for admins. That way we resolve the previous point and we use easyadmin to admin the links that is more powerful that custom controllers (we still will be able to create custom short urls, search by filter, etc).

**Review by thijskh — COMMENTED** [review]
As above

**Pull request closed without merging**
