### PR TITLE
Refactorize short generation

### PR DESCRIPTION
**Pull request by sgomez**
This PR create commands than implements two use cases:

- Create a random short url
- Create a custom short url

The commands will be dispatched from the applications ports: web application, JSON API, console commands...

Pending:

* [x] Add tests

### CODE REVIEW

**Comment by sgomez** [comment]
Added basic test functionality. I'm not very proud with the test design, but it is something I can improve in future PR. Behat configuration is based in [Sylius](https://github.com/Sylius/Sylius) project. Sylius has a great Behat design and I'd like to get more ideas from them.

**Comment by sgomez** [comment]
The code is refactorized, the use cases are moved to src/MessageHandler/* and controllers only can dispatch messages. Ready to review and discuss. Test will be improved in nexts PR.

**Comment by thijskh** [comment]
Code looks OK, will test a bit further.

**Review by thijskh — APPROVED** [review]

**Comment by thijskh** [comment]
Before merging, we should probably ensure that long urls with non-http(s) schemes are also accepted.

**Comment by sgomez** [comment]
@thijskh I rebased to use the new LongUrl validator and I added tests to check that all is working

**Review by thijskh — APPROVED** [review]

**Pull request merged**
