### PR TITLE
Update to Symfony 5.2

### PR DESCRIPTION
**Pull request by sgomez**
Update dependencies to Symfony 5.2

The composer.lock is builded with php 7.2. This version is out of maintenance, we should move to PHP 7.4 at least.

### CODE REVIEW

**Comment by thijskh** [comment]
We run Debian stable which has years of 7.3 support ahead of us.

**Comment by sgomez** [comment]
I said that because symfony.lock reports that we are using php 7.2. I can update the PR or send another one with php 7.3 but we should use the same version in all development environments.

**Comment by thijskh** [comment]
If it's up to me the code must run on Debian stable (and I don't think that's an unreasonable demand).

We can pick one version between ourselves but since we expect people to install the code themselves we must be prepared to support more than one.

**Comment by sgomez** [comment]
The application should support at least "php >= 7.2.5,<8.0" because it is configured in `composer.json`. Right now `php >= 8.0` it is not supported (yet, there are a pending conflict to be resolved in doctrine migrations).

The point is that all developers should use the same version or we will create different `composer.lock` and `symfony.lock` each time we install a new dependency.

I think we can keep working with PHP7.2 and left the decision to use a higher version in production to deployers. So if you are ok updating symfony, can you merge the PR? Thanks.

**Review by thijskh — APPROVED** [review]

**Pull request merged**
